### ISSUE TITLE
Setting node["chef_client"]["interval"] seems to be ignored for Windows service

### ISSUE THREAD

**Issue by adamlau** [opscode-cookbooks/chef-client#235]
I installed chef-client 12.0.3 via bootstrap onto a Windows 8.1 machine. I used the default chef-client recipe to install the windows chef-client service. I'm trying to set the interval for the service to run to 5 mins.

I have a base role set for the windows node:

    name "base"
    description "Base role"
    run_list "recipe[chef-client]"
    default_attributes 
    override_attributes "chef_client" => { "interval" => "300" }

The chef-client windows service gets installed correctly but it runs at the default of 1800 seconds. I've tried a few different ways of setting the attribute but nothing seems to budge it from the default.

The documentation (https://github.com/opscode-cookbooks/chef-client#attributes) says:
> The following attributes affect the behavior of the chef-client program when running as a service through one of the service recipes, or in cron with the cron recipe, or are used in the recipes for various settings that require flexibility.
>
> * node["chef_client"]["interval"] - Sets Chef::Config[:interval] via command-line option for number of seconds between chef-client daemon runs. Default 1800.

I've looked through the source code of the chef-client recipe and executable but can't find how the interval is set via command-line option when using the windows service recipe. Do I have to set the interval attribute myself in client.rb?

**Comment by jfbibeau** [comment]
Having the same issue on Windows 7...

I have the following in my wrapper cookbook that invokes the chef-client recipe:

```
default['chef_client']['interval'] = '172800'
default['chef_client']['splay'] = '3600'
```

Works on Linux fine, but on Windows the service is stuck to 1800 seconds. I can confirm because at the end of the converge, the service prints:

```
[2015-01-14T08:35:12-08:00] INFO: Next chef-client run will happen in 1800.3427924620066 seconds
```

**Comment by echohack** [comment]
+1 here. This is effecting all Windows boxes in our infrastructure, including Windows 2008R2, W7, and 2012R2.

Setting a policy that ALL nodes can follow is super important for us so we can determine the check-in behavior of the nodes.

**Comment by juliandunn** [comment]
It's because the current command to set up a Windows service predates the ability of the service manager to handle `-i` and `-s` flags for interval and splay respectively:

https://github.com/opscode-cookbooks/chef-client/blob/master/recipes/windows_service.rb#L33

I would take a PR to add them and populate using the attributes.

**Comment by echohack** [comment]
@juliandunn doesn't this then cause manual runs to adhere to the config settings? (Such as using WinRM to kick off chef-client, or logging onto the box and kicking off the Chef client).

**Comment by juliandunn** [comment]
@echohack Yes, but since a splay isn't applied to a manual run, it makes no difference.

**Comment by echohack** [comment]
@juliandunn 

In my testing, splays are applied to manual runs. If you don't have a splay, it will execute the manual run immediately:

![screen shot 2015-02-06 at 3 32 27 pm](https://cloud.githubusercontent.com/assets/3253989/6089539/17a3cdce-ae19-11e4-8de5-b74955c114ca.png)
![screen shot 2015-02-06 at 3 55 31 pm](https://cloud.githubusercontent.com/assets/3253989/6089538/179b6bb6-ae19-11e4-8948-e548a826111b.png)

```
[root@my-server ~]# cat /etc/chef/client.rb
chef_server_url "https://chef.example.com/organizations/example"
interval 7200
splay 1200
validation_client_name "example-validator"
# Using default node name (fqdn)


Dir.glob(File.join("/etc/chef", "client.d", "*.rb")).each do |conf|
  Chef::Config.from_file(conf)
end
```

C:\Chef\client.rb

```
[root@ads-s-af1 ~]# cat /etc/chef/client.rb
chef_server_url "https://chef.example.com/organizations/example"
interval 7200
splay 1200
validation_client_name "example-validator"
# Using default node name (fqdn)


Dir.glob(File.join("/etc/chef", "client.d", "*.rb")).each do |conf|
  Chef::Config.from_file(conf)
end
```

**Comment by juliandunn** [comment]
@echohack what version of Chef are you on? I feel like this behavior was fixed recently so that splay isn't evaluated till after the run.

**Comment by echohack** [comment]
@juliandunn 

I did some more testing and it turns out chef-client 12.0.3-1 simply changes the problem. If the interval exists in the client.rb, then it will be run first. If not, then the splay will be run.

 On 11.8.6, if the splay is blank in the client.rb then the interval occurs at the end of the run.

11.8.6
Windows:
![screen shot 2015-02-09 at 4 00 14 am](https://cloud.githubusercontent.com/assets/3253989/6105818/476cc828-b010-11e4-9354-9effe71079a5.png)

Linux: (not really a problem, since you can use command line settings for this, but just to demonstrate explicitly setting in the client.rb...)
![screen shot 2015-02-09 at 4 39 33 am](https://cloud.githubusercontent.com/assets/3253989/6106373/b5a45856-b015-11e4-8b32-a4b01da8918a.png)


12.0.3
Windows: 
![screen shot 2015-02-09 at 6 26 20 am](https://cloud.githubusercontent.com/assets/3253989/6108031/a07152c2-b024-11e4-838c-f57246fd7f63.png)

Linux: (not really a problem, since you can use command line settings for this, but just to demonstrate explicitly setting in the client.rb...)
![screen shot 2015-02-09 at 4 30 45 am](https://cloud.githubusercontent.com/assets/3253989/6106390/d5ef4210-b015-11e4-933b-e37c4b967500.png)

And with the interval set to blank (just Windows for this example):

![screen shot 2015-02-09 at 6 29 25 am](https://cloud.githubusercontent.com/assets/3253989/6108090/20d64b3e-b025-11e4-8abf-c478041ee6c4.png)

**Comment by juliandunn** [comment]
Thanks for doing that testing @echohack. So I guess I was wrong in https://github.com/opscode-cookbooks/chef-client/issues/235#issuecomment-72618486 :grin:

So back to the original problem as reported here. You're saying that Chef Client on Windows ignores an interval set in `client.rb`?

**Comment by echohack** [comment]
Windows won't respect the interval/splay set on the node.

To quoth the documentation:
> node["chef_client"]["interval"] - Sets Chef::Config[:interval] via command-line option for number of seconds between chef-client daemon runs. Default 1800.
>node["chef_client"]["splay"] - Sets Chef::Config[:splay] via command-line option for a random amount of seconds to add to interval. Default 300.

This leads to the "workaround" of wanting to set it in the client.rb using ['chef_client']['config']['interval'] and ['chef_client']['config']['splay'], but this makes manual runs impossible to instantly execute. Windows WILL respect the settings for regular check-in runs in the client.rb.

Personally we think it's more painful to have to wait for manual runs (if we do a manual run, we want it to go NOW), so we choose just to use the default built in 30 minutes interval and 5 minute splay... but we'd like to be able to set this so it can be in accordance with our policy in our base cookbook.

**Comment by juliandunn** [comment]
Can't you run a manual run using `chef-client -s 0` to ignore any set splay in `client.rb`?

I guess I'm not really seeing how this behavior is distinct from the behavior on Linux/UNIX.

**Comment by echohack** [comment]
> Can't you run a manual run using chef-client -s 0 to ignore any set splay in client.rb?

Not really... if you ignore the splay it will simply use the interval on the chef-client 12.0.3-1. (Chef 11.18.6 client doesn't do this, but as you mentioned earlier, this is a bug). Waiting 30 minutes or 2 hours or w/e is not acceptable for doing a manual run.

> I guess I'm not really seeing how this behavior is distinct from the behavior on Linux/UNIX.

Linux/UNIX will respect the node["chef_client"]["interval"]  and node["chef_client"]["splay"] settings. Windows will NOT. 

...This means you are forced to set the values in the config, which results in not having manual runs set correctly. This second behavior is identical on Windows / Linux / UNIX.

**Comment by jfbibeau** [comment]
Agreed! We should fix the root cause (interval/splay not applying on Windows), and not concern ourselves too much of fixing various behaviors related to the workaround.

**Comment by juliandunn** [comment]
I'm increasingly starting to read this as a problem with the Chef client itself, not this cookbook...?

**Comment by jfbibeau** [comment]
You tell us! If the reason why interval/splay doesn't affect the Windows service is because of a bug/feature not implemented in the chef-client, then I can post the issue on their repo instead. My first impression was a bug in the chef-client cookbook, but if it's a limitation of chef-client, then maybe we update the README to indicate it's not supported in Windows, and handle the ticket on the chef-client side. What do you think?

**Comment by jeremiahsnapp** [comment]
@juliandunn Why don't put the `-i <value>` directly in the registry entry for the chef-client service in order to avoid setting it in `client.rb`?

That seems like it would be the closest analogue to what we do when setting the interval for the Linux chef-client service.

**Comment by juliandunn** [comment]
@jeremiahsnapp What registry key does it use?

That detail aside, it sounds like there are two distinct issues described in this issue that need further investigation/triage:

1. Manually running Chef Client on Windows causes an unnecessary delay, because `interval` and/or `splay` sleep is read from `client.rb` and that wait time is prepended to the run.
2. The interval, ironically, is ignored when setting up the Chef Windows service, because `chef-service-manager` doesn't understand `interval` and there isn't a delightful way to teach it to do so.

Is that a decent summary of what's going on here? Neither of these seem to be problems with the cookbook, just problems in core Chef.

**Comment by echohack** [comment]
@juliandunn Seems reasonable.

**Comment by jeremiahsnapp** [comment]
@juliandunn I spent some time investigating this and I have a more thorough description of the problem as well as a proposed workaround until the real problem gets fixed.

When chef-client 12 is configured with an interval and splay it waits (sleeps) for the assigned time and then starts the chef-client run. This behavior is new, chef-client 11 made its run first and then waited the assigned time. This change in behavior is deliberate and the reason is explained [here](https://github.com/chef/chef/issues/3305#issuecomment-97549972). However, if the chef-client service is configured incorrectly the new chef-client 12 behavior can undesirably cause manual chef-client runs to be delayed as well.

To properly configure the chef-client as a service that runs on an interval without causing manual runs to also abide by that interval you configure the interval and splay as options in the command that starts the chef-client service instead of in the `client.rb`. This is exactly how the `chef-client` cookbook configures Linux systems as long as you use the recommended attributes `node['chef_client']['interval']` and `node['chef_client']['splay']`.

If you use the attributes `node['chef_client']['config']['interval']` and `node['chef_client']['config']['splay']` instead the settings will be made in `client.rb` which undesirably impacts manual chef-client runs.

So using the `chef-client` cookbook and attributes correctly as described in its README gives users what they want on Linux systems. Unfortunately, the current way the `chef-client` cookbook installs the Windows service does not properly use the attributes `node['chef_client']['interval']` and `node['chef_client']['splay']`. Effectively the attributes are ignored and the Windows service runs on a default interval of 1800 seconds.

The Window service can be configured in a manner similar to the Linux service. The interval and splay can be set in the following registry key which defines the command that starts the Windows service.

```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client\ImagePath
```

Currently the default value for `ImagePath` is `"C:\opscode\chef\embedded\bin\ruby" "C:\opscode\chef\bin\chef-windows-service"  -c C:\chef\client.rb -L C:\chef\log\client.log`. Simply appending ` -i 700 -s 30` to that value and restarting the service correctly sets the interval and splay for the service while still allowing for manually running chef-client immediately.

Some work needs to be done to both the `chef-client` cookbook as well as the Chef Client code in order to really fix this but it doesn't look very complicated.

The following link shows the `chef-service-manager` command that the `chef-client` cookbook uses to install chef as a service. This is where the chef-client cookbook needs to append new options for the interval and splay.

https://github.com/opscode-cookbooks/chef-client/blob/v4.3.0/recipes/windows_service.rb#L33

The following links show where the new interval and splay options would need to be defined in the `chef-service-manager` code.

https://github.com/chef/chef/blob/12.4.0/lib/chef/application/windows_service_manager.rb#L45-L55
https://github.com/chef/chef/blob/12.4.0/lib/chef/application/windows_service_manager.rb#L107-L109

In the meantime I created the following recipe as a workaround for those who absolutely can't wait for the fix to be released. The `ruby_block` and `registry_key` resources append the interval and splay to the value in the `ImagePath` registry key and then restart the chef-client service.

```
node.override["chef_client"]["interval"] = 700
node.override["chef_client"]["splay"] = 30

include_recipe 'chef-client::config'
include_recipe 'chef-client::service'

ruby_block 'set_imagepath_data' do
  block do
    imagepath_data = ''
    imagepath = registry_get_values('HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client' ).select { |k| k[:name] == 'ImagePath' }.first
    if imagepath.has_key?(:data)
      segments = imagepath[:data].split(/\s+-/)
      segments.each_with_index do |segment, index|
        if index == 0
          imagepath_data += segment
        else
          imagepath_data += " -#{segment}" unless segment.start_with?('i', '-interval', 's', '-splay')
        end
      end
    end
    resources('registry_key[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client]').values(
      [{
         :name => 'ImagePath',
         :type => :expand_string,
         :data => "#{imagepath_data} -i #{node['chef_client']['interval']} -s #{node['chef_client']['splay']}"
       }]
    )
  end
  action :run
  notifies :create, 'registry_key[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client]', :immediately
  only_if { registry_key_exists?('HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client') }
end

registry_key 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client' do
  values [{
            :name => 'ImagePath',
            :type => :expand_string,
            :data => ''
          }]
  action :nothing
  notifies :restart, 'service[chef-client]', :immediately
end
```

**Comment by spuder** [comment]
I'm also running into this bug, and it is a big one for me. Since I'm not using splay, I figured I could work around it by using the config recipe, to modify the client.rb file

default.rb
```
include_recipe 'chef-client'
include_recipe 'chef-client::delete_validation'
include_recipe 'chef-client::config'
```

In my role/environment attributes
```
  "chef_client": {
    "config": {
      "interval": 555
    }
```
But it throws this error. 

    can't convert String into time interval

![screenshot 2015-07-10 12 20 36](https://cloud.githubusercontent.com/assets/242382/8625794/1c832674-26fe-11e5-9592-aee24b93bf91.png)

Also tried 

```
  "chef_client": {
    "config": {
      "interval": 555,
      "splay": 44
    }
```

and
```
  "chef_client": {
    "config": {
      "interval": "555"
    }
```


Has anyone else seen this while trying to work around this bug?

**Comment by aarsan** [comment]
Has Chef acknowledged this as a bug?

**Comment by jaym** [comment]
@aarsan what version of the cookbook are you using?

**Comment by aarsan** [comment]
4.2.4 .. will try the latest version. thanks

**Comment by smurawski** [comment]
This is resolved in version 4.3.1, which is available from Supermarket now.

**Comment by ajeba99** [comment]
@smurawski 

I've been testing this and I can confirm this is indeed **not** fixed.  I am running 4.3.1 with chef-client 12.4.1.

I have a role called "all-servers", of which, inside I am trying to get chef-client for windows configured in either a service or task manner running every 3 minutes.  (just for testing purposes)

The only way I could reliably get away from the 1800 second default was to hard edit the attributes defaults in the chef-client cookbook itself.  I hard edited the interval to 10 minutes.  But this is not a welcome long term solution.

Here is my chef server's config dump for the chef_client role.
````
PS C:\opscode\chef-repo> knife role show all-servers
chef_type:           role
default_attributes:
description:
env_run_lists:
json_class:          Chef::Role
name:                all-servers
override_attributes:
  chef_client:
    config:
      interval: 180
      splay:    30
run_list:
  recipe[chef-client::config]
  recipe[chef-client::windows_service]
````
Here is my override json from the all-servers role ...
````
{
  "chef_client": {
    "config": {
      "interval": 180,
      "splay": 30
    }
  }
}
````
I am trying to load chef-client::config & chef-client::windows_service / chef-client::task.  When it's a task the task is set to a 10 minute schedule.  When it's a service, the event log consistently says something to the effect, "... next chef-client run will happen in 629 seconds".'

However, my overrides are being added to the c:\chef\client.rb file as ...
````
chef_server_url "https://api.opscode.com/organizations/jimp"
client_fork true
interval 180
log_location "C:/chef/log/client.log"
splay 30
validation_client_name "chef-validator"
verify_api_cert true
node_name "DB1"
````
Yet they are clearly getting ignored.

Ergo, vis-a-vis, concordantly please fix.

**Comment by dparkar** [comment]
Was this finally fixed ? I am still seeing similar behavior with Chef-Client v12.5.1 and Chef-Client cookbook version v4.3.3 on a Windows Server 2012 R2.

**Comment by artisticcheese** [comment]
Can somebody comment what exactly needs to be put and where for this to work. I have a role where I specifed override attributes 

```
{
  "chef_client": {
    "config": {
      "interval": 180,
      "splay": 30
    }
  }
}
```

Node has this added as top Run List but this data does not make it to client.rb file on a node. The rest of runlist works fine but this attribute never being set or overridden.

**Comment by raycrawford** [comment]
dparkar, how did you get the override to work?  I can set it for Linux with the following addition to my default attributes file:

default['chef_client']['interval'] = '180'
default['chef_client']['splay'] = '30'

but windows is ignoring it.

 Thanks.

**Comment by tiagobevilaqua** [comment]
Why this issue is still closed if the problem still exists?
